name: Release version

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version'
        required: true
        default: 'warning'
        type: choice
        options:
          - fix
          - minor
          - major

jobs:

  release-version:
    runs-on: ubuntu-latest
#    needs: [build]
    permissions: write-all

    steps:
      - uses: actions/checkout@v3

      - name: Test
        run: echo "fffff"